apiVersion: v1
kind: Service
metadata:
  name: minio-service
  namespace: ggr
spec:
  type: NodePort
  ports:
    - nodeport: 31587 #
      port: 9000 #
      targetPort: 9000 #
      protocol: TCP
  selector:
    app: minio   
